
#version: '3.8' # Mantenerlo por claridad, aunque v2 lo ignore
services:
  # Servicio de la base de datos PostgreSQL
  db:
    image: postgres:16 # Puedes usar :13-alpine para una imagen más ligera si lo prefieres
    container_name: docker_postgres # Nombre fijo para el contenedor de la BD
    ports:
      - "5432:5432" # Mapea el puerto 5432 del contenedor al 5432 de tu máquina local
    env_file: # Carga las variables de entorno desde .env para la BD
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}   # <- aqui se crea crypto_db automaticamente

    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data: # Define el volumen de datos para PostgreSQL